/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseTab: typeof import('./src/components/tab/BaseTab.vue')['default']
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Deliveries: typeof import('./src/components/dashboard/Deliveries.vue')['default']
    FilterFrozenTable: typeof import('./src/components/table/FilterFrozenTable.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Fluid: typeof import('primevue/fluid')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    QuickAction: typeof import('./src/components/dashboard/QuickAction.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    ReusableTable: typeof import('./src/components/table/ReusableTable.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleCallTable: typeof import('./src/components/table/SampleCallTable.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Tree: typeof import('primevue/tree')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
